env:
  browser: true
  es2021: true
extends:
  - airbnb
  - prettier
  - plugin:node/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
rules: {
    "no-unused-vars": "warn",
    "no-console": "warn",
    "func-names": "warn",
    "no-process-exit": "warn",
    "object-shorthand": "warn",
    "class-methods-use-this": "warn",
    "no-restricted-syntax":"warn",
    "no-else-return":"warn",
    "prefer-arrow-callback":"warn"
  }
