env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:node/recommended
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
rules: {
    "prettier/prettier": "error",
    "no-unused-vars": "warn",
    "no-plusplus": "off",
    "no-console": "off",
    "func-names": "off",
    "no-process-exit": "warn",
    "object-shorthand": "warn",
    "class-methods-use-this": "warn",
    "no-restricted-syntax": "warn",
    "no-else-return": "warn",
    "prefer-arrow-callback": "warn",
    "camelcase": "warn",
    "import/extensions":"off",
    "node/no-unsupported-features/es-syntax": "off",
    "import/prefer-default-export": "off"
  }
ignorePatterns:
  - node_modules